### ISSUE TITLE
Input Files

### ISSUE THREAD

**Issue by Ezharjan** [jinhojin/CARLA_LSTM#1]
Hello!
What were your input files and how were they collected?
Like `processing116.csv`, what's inside the file? Would you mind sharing the inside of the collected data as an example?

**Comment by Ezharjan** [comment]
> Hello! What were your input files and how were they collected? Like `processing116.csv`, what's inside the file? Would you mind sharing the inside of the collected data as an example?

Is the CSV file created via [this](https://github.com/jinhojin/Carla_recording) repository available for using this repository for the evaluation?

**Comment by jinhojin** [comment]
> Hello! What were your input files and how were they collected? Like `processing116.csv`, what's inside the file? Would you mind sharing the inside of the collected data as an example?

Hello! @Ezharjan 
Yes, you can make the CSV file via https://github.com/jinhojin/Carla_recording
You can use the code, but it is not that user-friendly because I do not intend to make it public then.
I do not have an example CSV file because I deleted it when I left the lab where I used to work, but I remember them as CSV files containing the speed, location, gear, and other information about the vehicle.

**Comment by Ezharjan** [comment]
> > Hello! What were your input files and how were they collected? Like `processing116.csv`, what's inside the file? Would you mind sharing the inside of the collected data as an example?
> 
> Hello! @Ezharjan Yes, you can make the CSV file via https://github.com/jinhojin/Carla_recording You can use the code, but it is not that user-friendly because I do not intend to make it public then. I do not have an example CSV file because I deleted it when I left the lab where I used to work, but I remember them as CSV files containing the speed, location, gear, and other information about the vehicle.

Thanks!

Do you remember the order of the names of each keys in the input CSV file?
I'm going to record and collect the data myself and use your script for evaluation.

**Comment by Ezharjan** [comment]
> > > Hello! What were your input files and how were they collected? Like `processing116.csv`, what's inside the file? Would you mind sharing the inside of the collected data as an example?
> > 
> > 
> > Hello! @Ezharjan Yes, you can make the CSV file via https://github.com/jinhojin/Carla_recording You can use the code, but it is not that user-friendly because I do not intend to make it public then. I do not have an example CSV file because I deleted it when I left the lab where I used to work, but I remember them as CSV files containing the speed, location, gear, and other information about the vehicle.
> 
> Thanks!
> 
> Do you remember the order of the names of each keys in the input CSV file? I'm going to record and collect the data myself and use your script for evaluation.



> > > Hello! What were your input files and how were they collected? Like `processing116.csv`, what's inside the file? Would you mind sharing the inside of the collected data as an example?
> > 
> > 
> > Hello! @Ezharjan Yes, you can make the CSV file via https://github.com/jinhojin/Carla_recording You can use the code, but it is not that user-friendly because I do not intend to make it public then. I do not have an example CSV file because I deleted it when I left the lab where I used to work, but I remember them as CSV files containing the speed, location, gear, and other information about the vehicle.
> 
> Thanks!
> 
> Do you remember the order of the names of each keys in the input CSV file? I'm going to record and collect the data myself and use your script for evaluation.

Or can you at least tell me what are the meanings of these abbriviated keys?
```
x_ev, y_ev, yaw_ev, vx_ev, vy_ev, 
x_tv, y_tv, yaw_tv, vx_tv, vy_tv, 
x_s1, y_s1, yaw_s1, vx_s1, vy_s1, 
x_s2, y_s2, yaw_s2, vx_s2, vy_s2, 
x_s3, y_s3, yaw_s3, vx_s3, vy_s3, 
x_s4, y_s4, yaw_s4, vx_s4, vy_s4, 
x_s5, y_s5, yaw_s5, vx_s5, vy_s5, 
x_s6, y_s6, yaw_s6, vx_s6, vy_s6
```

**Comment by jinhojin** [comment]
> > > > Hello! What were your input files and how were they collected? Like `processing116.csv`, what's inside the file? Would you mind sharing the inside of the collected data as an example?
> > > 
> > > 
> > > Hello! @Ezharjan Yes, you can make the CSV file via https://github.com/jinhojin/Carla_recording You can use the code, but it is not that user-friendly because I do not intend to make it public then. I do not have an example CSV file because I deleted it when I left the lab where I used to work, but I remember them as CSV files containing the speed, location, gear, and other information about the vehicle.
> > 
> > 
> > Thanks!
> > Do you remember the order of the names of each keys in the input CSV file? I'm going to record and collect the data myself and use your script for evaluation.
> 
> > > > Hello! What were your input files and how were they collected? Like `processing116.csv`, what's inside the file? Would you mind sharing the inside of the collected data as an example?
> > > 
> > > 
> > > Hello! @Ezharjan Yes, you can make the CSV file via https://github.com/jinhojin/Carla_recording You can use the code, but it is not that user-friendly because I do not intend to make it public then. I do not have an example CSV file because I deleted it when I left the lab where I used to work, but I remember them as CSV files containing the speed, location, gear, and other information about the vehicle.
> > 
> > 
> > Thanks!
> > Do you remember the order of the names of each keys in the input CSV file? I'm going to record and collect the data myself and use your script for evaluation.
> 
> Or can you at least tell me what are the meanings of these abbriviated keys?
> 
> ```
> x_ev, y_ev, yaw_ev, vx_ev, vy_ev, 
> x_tv, y_tv, yaw_tv, vx_tv, vy_tv, 
> x_s1, y_s1, yaw_s1, vx_s1, vy_s1, 
> x_s2, y_s2, yaw_s2, vx_s2, vy_s2, 
> x_s3, y_s3, yaw_s3, vx_s3, vy_s3, 
> x_s4, y_s4, yaw_s4, vx_s4, vy_s4, 
> x_s5, y_s5, yaw_s5, vx_s5, vy_s5, 
> x_s6, y_s6, yaw_s6, vx_s6, vy_s6
> ```

x and y is location of vehicle. yaw is yaw data given by Carla, vx and vy is velocity of each axis. All data is given by Carla. 
ev, tv, s1.….. is type of vehicle. In our research, we used 8 vehicles including target vehicle (tv),   our vehicle(ev), and close 6 vehicles (1 to 6)

**Comment by Ezharjan** [comment]
Thanks!

**Comment by Ezharjan** [comment]
Would you mind me citing your repository in my paper?
How to cite it? (Since this repository lacks LICENSE or any citable information.)
Thanks!

**Comment by Ezharjan** [comment]
A kind reminder: You can upload a license or citation information so that everyone can cite your repository.

**Comment by jinhojin** [comment]
@Ezharjan 
Thanks for the information.
I've just added citation.cff in the repository.
Could you please use that to cite the code in your paper? Thank you.

**Comment by Ezharjan** [comment]
> @Ezharjan Thanks for the information. I've just added citation.cff in the repository. Could you please use that to cite the code in your paper? Thank you.

Thanks!
